# -*- coding: utf-8 -*-
"""AULA 1  E 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VKdsgvn6r3BtvfpvRca91YFm8-LJ3lJN
"""

# mini curso introdução a python
# Ruan luciano

# tipo Inteiro ok
# tipo Reais ok
# tipo booleanos ok
# tipo caracteres (strings) ok

#r = 'luciano'
#print(type(r))
#r = 6.5
#l = 5
#print('ola mundo')

#r = 8
#print(r)

#nota1 = 5
#nota2 = 7
#print( nota1 + nota2 )

#nota1 = 6
#nota2 = 8
#nota3 = 6
#nota4 = 7

#print(nota1+nota2+nota3+nota4 // 4)